// <auto-generated />
namespace Assignment_3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class albumtrackinvoicemediaadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(albumtrackinvoicemediaadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201809292116332_album-track-invoice-media-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
